---
- hosts: '{{ inventory }}'
  become: True
  become_user: root
  gather_facts: yes
  vars:
    ansible_ssh_user: ec2-user
    users:
    - username: "st"
      groups: "adm,wheel"
      comment: "Stephen Tse"
    - username: "lc"
      groups: "adm,wheel"
      comment: "Leo Chen"
    - username: "rj"
      groups: "adm,wheel"
      comment: "Rongjian Lan"
    - username: "md"
      groups: "adm,wheel"
      comment: "Minh Doan"
    - username: "ea"
      groups: "adm,wheel"
      comment: "Edgar Aroutiounian"
    - username: "dm"
      groups: "adm,wheel"
      comment: "Daniel Van Der Maden"
    - username: "aw"
      groups: "adm,wheel"
      comment: "Andy Wu"
    - username: "gu"
      groups: "adm,wheel"
      comment: "Ganesha Upadhyaya"
    - username: "yc"
      groups: "adm,wheel"
      comment: "Yishuang Chen"
    - username: "hb"
      groups: "adm,wheel"
      comment: "Xuan Huang"
    - username: "jl"
      groups: "adm,wheel"
      comment: "Janet Liang"
    - username: "jz"
      groups: "adm,wheel"
      comment: "Jian Zhen"
    - username: "jw"
      groups: "adm,wheel"
      comment: "John Whitton"
    - username: "sj"
      groups: "adm,wheel"
      comment: "Sebastian Johnsson"
    - username: "lw"
      groups: "adm,wheel"
      comment: "Lei Wang"
    - username: "dw"
      groups: "adm,wheel"
      comment: "Dennis Won"
    - username: "as"
      groups: "adm,wheel"
      comment: "Andrew Song"
    - username: "cf"
      groups: "adm,wheel"
      comment: "Cem Fahliogullari"
    - username: "sd"
      groups: "adm,wheel"
      comment: "Sahil Dewan"
    - username: "hd"
      groups: "adm,wheel"
      comment: "Haodi Jiang"
    - username: "lj"
      groups: "adm,wheel"
      comment: "Jiang Li"
    - username: "nw"
      groups: "adm,wheel"
      comment: "Nick White"
    - username: "ns"
      groups: "adm,wheel"
      comment: "Niteesh Settypalli"
    remove_users:
    - "foo"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item.username }}"
      groups: "{{ item.groups }}"
      create_home: yes
      state: "present"
    with_items: "{{ users }}"
  - name: "Remove old user accounts in remove_users"
    user:
      name: "{{ item }}"
      state: "absent"
    with_items: "{{ remove_users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item.username }}"
      key: "{{ lookup('file', '../vars/'+ item.username + '.key.pub') }}"
    with_items: "{{ users }}"
  - name: "Add each user to sudo"
    lineinfile:
      path: "/etc/sudoers.d/{{ item.username }}"
      line: '{{ item.username }} ALL=(ALL) NOPASSWD: LOG_INPUT: LOG_OUTPUT: ALL'
      state: present
      mode: 0440
      create: yes
      validate: '/usr/sbin/visudo -cf %s'
    with_items: "{{ users }}"
  - name: "Set includedir in sudoers"
    lineinfile:
      path: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"
  - name: "log sudo command"
    lineinfile:
      path: "/etc/sudoers"
      state: present
      regexp: "^%wheel"
      insertafter: '^%wheel'
      line: 'Defaults logfile=/var/log/sudo'
  - name: "log sudo-io per user"
    lineinfile:
      path: "/etc/sudoers"
      state: present
      regexp: "^%wheel"
      insertafter: '^%wheel'
      line: 'Defaults iolog_dir=/var/log/sudo-io/%{user}'
      validate: "/usr/sbin/visudo -cf %s"
  - name: "Add shell customization"
    lineinfile:
      path: "/etc/profile.d/sh.local"
      state: present
      regexp: "#Add"
      insertafter: "#Add"
      line: 'PATH=${PATH}:/usr/local/go/bin'

# vim: set expandtab:ts=4
